package com.uniq.tms.tms_microservice.modules.userManagement.adapter;

import com.uniq.tms.tms_microservice.modules.locationManagement.entity.LocationEntity;
import com.uniq.tms.tms_microservice.modules.locationManagement.entity.UserLocationEntity;
import com.uniq.tms.tms_microservice.modules.organizationManagement.entity.RoleEntity;
import com.uniq.tms.tms_microservice.modules.organizationManagement.entity.SubscriptionEntity;
import com.uniq.tms.tms_microservice.modules.userManagement.dto.GroupDto;
import com.uniq.tms.tms_microservice.modules.userManagement.dto.UserNameEmailDto;
import com.uniq.tms.tms_microservice.modules.userManagement.entity.*;
import com.uniq.tms.tms_microservice.modules.userManagement.dto.UserNameSuggestionDto;
import com.uniq.tms.tms_microservice.modules.userManagement.enums.MemberType;
import com.uniq.tms.tms_microservice.modules.workScheduleManagement.entity.WorkScheduleEntity;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

public interface UserAdapter {
    List<GroupEntity> getAllGroup(String orgId);
    UserEntity saveUser(UserEntity entity);
    UserEntity updateUser(UserEntity userId);
    Optional<UserEntity> findByEmail(String email);
    void updatePassword(UserEntity user);
    Optional<UserEntity> findById(String userId);
    Optional<RoleEntity> findById(Long roleId);
    void deactivateUserById(String userId, String orgId);
    void deleteUser(UserEntity user);
    GroupEntity saveGroup(GroupEntity entity);
    boolean findByGroup(String teamName, String orgId);
    int updateUserGroupType(String userId, Long groupId, String type);
    void deleteMember(Long groupId, List<String> memberId);
    void deleteGroup(Long groupId, String orgId);
    List<UserEntity> getMembers(String orgId, Long roleId);
    List<UserEntity> getMembersByRole(String orgId, List<Integer> higherRoleIds);
    List<GroupDto> getUserGroups(String userId, String orgId);
    List<UserGroupEntity> getGroupMembersByGroupId(Long groupId, String orgId);
    List<UserEntity> getUsersByIds(List<String> userIds, String orgId);
    Optional<UserEntity> findByMobileNumber(String mobileNumber);
    List<UserEntity> getAllUsers(String orgId, String userIdFromToken, int hierarchyLevel);
    UserEntity getUserById(String userId);
    boolean existsGroupNameInOrganization(String groupName, String orgId, Long groupId);
    UserGroupEntity saveUserGroup(UserGroupEntity entity);
    List<UserGroupEntity> findByUserIdAndGroupId(String userId, Long groupId);
    void deleteSupervisorsByGroupId(Long groupId, String userId);
    void deleteByGroupId(Long groupId);
    List<Long> findGroupIdsBySupervisorId(String userIdFromToken);
    List<GroupDto> getAllgroups(String orgId);
    List<UserEntity> findUsersByGroupIds(List<Long> groupIds);
    List<UserEntity> findMembersByGroupIds(List<Long> filteredGroupIds, String userIdFromToken);
    SecondaryDetailsEntity saveSecondaryDetails(SecondaryDetailsEntity secondaryDetails);
    Optional<SecondaryDetailsEntity> findByMobileByMobile(String mobile);
    Optional<SecondaryDetailsEntity> findByEmailByEmail(String email);
    List<UserNameSuggestionDto> searchUserNamesContaining(String keyword);
    Optional<SecondaryDetailsEntity> findSecondaryUserById(String userId);
    boolean existsById(String userId);
    List<String> findSupervisorIdsByGroupId( Long groupId);
    Optional<GroupEntity> findByGroupId(Long groupId);
    List<String> findMemberIdsByGroupId(Long groupId);
    List<UserGroupEntity> getGroupUsersByGroupId(List<Long> groupIds, String orgId);
    List<UserNameSuggestionDto> getAllActiveUsers(String orgId, int heirarchyLevel);
    List<UserNameSuggestionDto> getAllGroupUsers(List<Long> groupIds, String orgId);
    Set<String> getAllMobileNumbers(String orgId);
    Set<String> getAllEmails(String orgId);
    List<UserEntity> saveAllUsers(List<UserEntity> users);
    List<SecondaryDetailsEntity> saveAllSecondaryDetails(List<SecondaryDetailsEntity> details);
    Map<String, Long> getGroupNameIdMap(String orgId);
    List<UserGroupEntity> saveAllUserGroups(List<UserGroupEntity> userGroups);
    Set<String> getAllSecondaryEmail(String orgId);
    Set<String> getAllSecondaryMobile(String orgId);
    UserEntity findUserByOrgIdAndUserId(String orgId, String userId);
    List<UserEntity> getUsersByRoles(Set<String> roles, String orgId);
    List<UserEntity> findUsersByRolesAndGroupIds(Set<String> roles, List<Long> supervisedGroupIds, String orgId);
    List<UserGroupEntity> findUserGroupByUserId(String userId);
    void deleteUserGroupByUserId(String userId, Set<Long> toDelete);
    void updateUserGroupByUserId(List<UserGroupEntity> newEntities);
    List<UserEntity> save(List<UserEntity> user);
    List<UserGroupEntity> findUserByOrganizationIdAndUserId(String orgId, String userId);
    UserSchemaMappingEntity create(UserSchemaMappingEntity userSchemaMappingEntity);
    UserSchemaMappingEntity findUserByEmail(String email);
    UserSchemaMappingEntity findUserByMobile(String mobile);
    String findByPlan();
    SubscriptionEntity saveSubscription(SubscriptionEntity subscriptionEntity);
    void saveAllMappings(List<UserSchemaMappingEntity> mappings);
    void saveAllSecondaryMappings(List<UserSchemaMappingEntity> secondaryMappings);
    UserSchemaMappingEntity update(UserSchemaMappingEntity mapping);
    Optional<UserSchemaMappingEntity> findUserByMobileAndOrgId(String mobile, String orgId);
    void saveUserHistory(UserHistoryEntity userHistoryEntity);
    void deleteUserFace(String userId);
    List<UserHistoryEntity> getUserHistoryLog(String userId);
    List<UserEntity> searchUsers(String keyword);
    void updateUserWorkSchedule(String scheduleId, String scheduleId1);
    void updateGroupWorkSchedule(String scheduleId, String scheduleId1);
    List<UserEntity> findUserByOrgIdAndRoleId(String orgId, int roleId);
    int countTotalMembers(String orgId);
    int countActiveMembers(String orgId);
    int countInactiveMembers(String orgId);
    List<UserEntity> findByUserId(List<String> userId);
    UserEntity save(UserEntity user);
    void deleteByGroupIds(List<Long> groupIds);
    void deleteGroups(List<Long> groupIds, String orgId);
    List<GroupEntity> findGroupsByIds(Set<Long> groupIds);
    List<UserGroupEntity> findUserGroupsByUsersAndGroups(Set<String> userIds, Set<Long> groupIds);
    void deactivateUsersByIds(List<String> userIds, String orgId);
    List<UserHistoryEntity> saveAllUserHistories(List<UserHistoryEntity> userHistoryEntities);
    Long getSubscribedUserLimit(String orgId);
    Long getCurrentUserCount(String orgId);
    Optional<LocationEntity> findLocationById(Long locationId);
    boolean exists(String userId, Long locationId);
    UserLocationEntity save(UserLocationEntity mapping);
    void bulkUpdateWorkSchedule(WorkScheduleEntity workSchedule, List<String> userIds, String orgId);
    List<UserNameEmailDto> findAdminAndSuperAdminNamesAndEmails();
    List<UserEntity> findByOrganizationIdAndActiveTrue(String orgId);
    int countActiveUsers(String orgId);
    void flush();
    long getUserCount(String organizationId, java.time.LocalDateTime start, java.time.LocalDateTime end);
    Set<String> getAllMappedEmails(String orgId);
    Set<String> getAllMappedMobiles(String orgId);
    List<UserEntity> getUsersByIds(List<String> userIds);
    List<String> findUserIdsByGroupIds(List<Long> groupIds);
    List<GroupEntity> getSupervisorGroups(String supervisorId);
    List<UserEntity>getGroupMembers(Long groupId);
    List<UserEntity>  getallUsers(String approverId);
    List<UserEntity> findusersInGroup(List<Long> groupIds, String userId);
    Optional<UserEntity>findSuperAdminByOrgId(String orgId);
    List<UserEntity> findByApproverId(String approverId);
    List<UserEntity>findAllById(List<String>userIds);
    void updateApproverForUsers( String approverId, List<String> requestedUserIds);
    Set<String> getAllSupervisorIds(List<Long> groupIds, String userId, String type);
    String findApproverIdByUserId(String userId);
    String getCalendarIdByUserId(String userId);
     void updateUserApprover(String newApproverId, List<String> userIds);

}
