spring.application.name=tms-microservice
server.port=${PORT:8080}

#
#spring.datasource.url=jdbc:postgresql://localhost:5432/tms_service
#spring.datasource.username=postgres
#spring.datasource.password=$Rotor1994

# Heroku production
spring.datasource.url=jdbc:postgresql://ccj2ci9okh6spb.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfghhmlakj95ii
spring.datasource.username=u2ni8hq20b502n
spring.datasource.password=p88de628515ee81f122631df0608d7ab44fa0078ac1d0fd49c3f0fab34f1beae2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
database.type = postgres

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tickoratech@gmail.com
spring.mail.password=uiublmaybwizxwsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.prefix=classpath:/templates/

spring.web.resources.static-locations=classpath:/static/browser
# To avoid pattern conflict with {spring:...}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.hikari.maximum-pool-size=25
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=600000

java.net.preferIPv4Stack=true
server.forward-headers-strategy=framework
spring.cache.type=caffeine

csv.download.dir = ${user.dir}/uploads/temp/report/
csv.upload.dir = ${user.dir}/uploads/temp/bulkUser/

app.api.key = ${jwt.secret}
app.redis.url = ${REDISCLOUD_URL}
spring.redis.notify-keyspace-events=Ex

# Redis keys prefix
CACHE_LOCATION = location
CACHE_USER = users

