spring.application.name=tms-microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/tms_service
spring.datasource.username=postgres
spring.datasource.password=PostgreRoot
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
database.type = postgres

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tickoratech@gmail.com
spring.mail.password=uiublmaybwizxwsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.prefix=classpath:/templates/

spring.web.resources.static-locations=classpath:/static/browser
# To avoid pattern conflict with {spring:...}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000

java.net.preferIPv4Stack=true

server.forward-headers-strategy=framework
spring.cache.type=caffeine

