spring.application.name=tms-microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/tms_service
spring.datasource.username=postgres
spring.datasource.password=12345
#spring.datasource.url=jdbc:postgresql://caij57unh724n3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d1vjmlgig1h4dp
#spring.datasource.username=u73lkn4qjc3hev
#spring.datasource.password=p682a8e4cd03567a8778367e855a4b608811882fc4b798d4672db85bae8bfb20a
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
database.type = postgres

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tickoratech@gmail.com
spring.mail.password=uiublmaybwizxwsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.prefix=classpath:/templates/

spring.web.resources.static-locations=classpath:/static/browser
# To avoid pattern conflict with {spring:...}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000

java.net.preferIPv4Stack=true
server.forward-headers-strategy=framework
spring.cache.type=caffeine

csv.upload.dir=D:/UNIQ_Dev/tms-monorepo/src/main/resources/temp/

