package com.uniq.tms.tms_microservice.enums;

public enum PrivilegeConstants {

    REGISTER_ORGANIZATION,
    CREATE_NEW_MEMBER,
    LIST_OF_MEMBER,
    EDIT_MEMBER_PROFILE,
    EDIT_MEMBER_ROLE,
    DELETE_MEMBER,
    CREATE_NEW_GROUP,
    ADD_GROUP_MEMBER,
    EDIT_GROUP,
    DELETE_GROUP,
    REMOVE_GROUP_MEMBER,
    CREATE_WORK_SCHEDULE,
    VIEW_SCHEDULE,
    CREATE_NEW_LOCATION,
    VIEW_LOCATIONS,
    CHECK_IN_AND_OUT,
    STUDENT_ATTENDANCE,
    CAN_SEE_OWN_TIMESHEET,
    EDIT_TIMESHEET,
    CAN_SEE_ALL_TIMESHEETS,
    CAN_SEE_GROUP_LEVEL_TIMESHEETS,
    LOGIN_VIA_EMAIL,
    LOGIN_VIA_MOBILE,
    HAVE_SECONDARY_DETAILS,
    CAN_SEE_ALL_GROUPS,
    CAN_SEE_SUPERVISING_GROUPS
}
