package com.uniq.tms.tms_microservice.adapter;

import com.uniq.tms.tms_microservice.dto.GroupDto;
import com.uniq.tms.tms_microservice.dto.GroupsData;
import com.uniq.tms.tms_microservice.entity.GroupEntity;
import com.uniq.tms.tms_microservice.entity.LocationEntity;
import com.uniq.tms.tms_microservice.entity.RoleEntity;
import com.uniq.tms.tms_microservice.entity.UserEntity;
import com.uniq.tms.tms_microservice.entity.UserGroupEntity;
import com.uniq.tms.tms_microservice.model.Location;
import com.uniq.tms.tms_microservice.model.UserResponse;
import com.uniq.tms.tms_microservice.dto.UserNameSuggestionDto;
import com.uniq.tms.tms_microservice.entity.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

public interface UserAdapter {
    List<RoleEntity>getAllRole(Long orgId, int hierarchyLevel);
    List<GroupEntity> getAllGroup(Long orgId);
    UserEntity saveUser(UserEntity entity);
    UserEntity updateUser(UserEntity userId);
    Optional<UserEntity> findByEmail(String email);
    void updatePassword(UserEntity user);
    Optional<UserEntity> findById(Long userId);
    List<UserResponse> findByOrganizationId(Long orgId, int hierarchyLevel);
    void deactivateUserById(Long userId, Long orgId);
    void deleteUser(UserEntity user);
    GroupEntity saveGroup(GroupEntity entity);
    boolean findByGroup(String teamName, Long orgId);
    List<GroupsData> getGroupData(Long orgId);
    int updateUserGroupType(Long userId, Long groupId, String type);
    void deleteMember(Long groupId, Long memberId);
    void deleteGroup(Long groupId, Long orgId);
    List<UserEntity> getMembers(Long orgId, Long roleId);
    List<UserEntity> getMembersByRole(Long orgId, List<Integer> higherRoleIds);
    List<GroupDto> getUserGroups(Long userId, Long orgId);
    List<UserGroupEntity> getGroupMembersByGroupId(Long groupId, Long orgId);
    List<UserEntity> getUsersByIds(List<Long> userIds, Long orgId);
    Optional<UserEntity> findByMobileNumber(String mobileNumber);
    List<UserEntity> getAllUsers(Long orgId, Long userIdFromToken, int hierarchyLevel);
    UserEntity getUserById(Long userId);
    boolean existsGroupNameInOrganization(String groupName, Long orgId, Long groupId);
    UserGroupEntity saveUserGroup(UserGroupEntity entity);
    List<UserGroupEntity> findByUserIdAndGroupId(Long userId, Long groupId);
    void deleteSupervisorsByGroupId(Long groupId, Long userId);
    void deleteByGroupId(Long groupId);
    List<Long> findGroupIdsBySupervisorId(Long userIdFromToken);
    List<GroupDto> getAllgroups(Long orgId);
    List<UserEntity> findUsersByGroupIds(List<Long> groupIds);
    List<UserEntity> findMembersByGroupIds(List<Long> filteredGroupIds, Long userIdFromToken);
    SecondaryDetailsEntity saveSecondaryDetails(SecondaryDetailsEntity secondaryDetails);
    Optional<SecondaryDetailsEntity> findByMobileByMobile(String mobile);
    Optional<SecondaryDetailsEntity> findByEmailByEmail(String email);
    List<UserNameSuggestionDto> searchUserNamesContaining(String keyword);
    Optional<RoleEntity> findRoleById(Long roleId);
    Optional<SecondaryDetailsEntity> findSecondaryUserById(Long userId);
    boolean existsById(Long userId);
    List<Long> findSupervisorIdsByGroupId( Long groupId);
    Optional<GroupEntity> findByGroupId(Long groupId);
    List<Long> findMemberIdsByGroupId(Long groupId);
    LocationEntity findLocationById(Long locationId);
    List<UserGroupEntity> findUserByOrganizationIdAndUserId(Long organizationId, Long userId);
    List<RoleEntity> findAllWithPrivileges();
    List<UserGroupEntity> getGroupUsersByGroupId(List<Long> groupIds, Long orgId);
    List<UserNameSuggestionDto> getAllActiveUsers(Long orgId, int heirarchyLevel);
    List<UserNameSuggestionDto> getAllGroupUsers(List<Long> groupIds, Long orgId);
    Set<String> getAllMobileNumbers();
    Set<String> getAllEmails();
    Map<String, Long> getRoleNameIdMap();
    Map<String, Long> getLocationNameToIdMap();
    List<UserEntity> saveAllUsers(List<UserEntity> users);
    List<SecondaryDetailsEntity> saveAllSecondaryDetails(List<SecondaryDetailsEntity> details);
    Map<String, Long> getGroupNameIdMap();
    List<UserGroupEntity> saveAllUserGroups(List<UserGroupEntity> userGroups);
    RoleEntity getRoleWithPrivileges(Long roleId);
    Set<String> getAllSecondaryEmail();
    Set<String> getAllSecondaryMobile();
    UserEntity findUserByOrgIdAndUserId(Long orgId, Long userId);
    LocationEntity addLocation(Location location);
    PrivilegeEntity addPrivilege(PrivilegeEntity privilegeEntity);
    Optional<PrivilegeEntity> findPrivilegeById(Long privilegeId);
    void saveRole(RoleEntity role);
    List<UserEntity> getUsersByRoles(Set<String> roles, Long orgId);
    List<UserEntity> findUsersByRolesAndGroupIds(Set<String> roles, List<Long> supervisedGroupIds, Long orgId);
    void saveUserLocation(List<UserLocationEntity> userLocationEntities);
    List<UserLocationEntity> findUserLocationByUserId(Long userId);
    List<LocationEntity> findAllLocationById(List<Long> locationIds);
    void deleteUserLocationByUserId(Long userId, Set<Long> toDelete);
    void updateUserLocationByUserId(List<UserLocationEntity>newEntities);
    List<UserGroupEntity> findUserGroupByUserId(Long userId);
    void deleteUserGroupByUserId(Long userId, Set<Long> toDelete);
    void updateUserGroupByUserId(List<UserGroupEntity> newEntities);
    OrganizationEntity findByOrgId(Long orgId);
    boolean findByLocation(String name, Long orgId);
    List<UserEntity> findByRoleId(List<Long> roleIds, Long orgId);
    LocationEntity updateLocation(LocationEntity entity);
}
