package com.uniq.tms.tms_microservice.adapter;

import com.uniq.tms.tms_microservice.dto.GroupDto;
import com.uniq.tms.tms_microservice.entity.GroupEntity;
import com.uniq.tms.tms_microservice.entity.LocationEntity;
import com.uniq.tms.tms_microservice.entity.RoleEntity;
import com.uniq.tms.tms_microservice.entity.UserEntity;
import com.uniq.tms.tms_microservice.entity.UserGroupEntity;
import com.uniq.tms.tms_microservice.model.Location;
import com.uniq.tms.tms_microservice.dto.UserNameSuggestionDto;
import com.uniq.tms.tms_microservice.entity.*;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

public interface UserAdapter {
    List<RoleEntity>getAllRole(int hierarchyLevel);
    List<GroupEntity> getAllGroup(String orgId);
    UserEntity saveUser(UserEntity entity);
    UserEntity updateUser(UserEntity userId);
    Optional<UserEntity> findByEmail(String email);
    void updatePassword(UserEntity user);
    Optional<UserEntity> findById(String userId);
    void deactivateUserById(String userId, String orgId);
    void deleteUser(UserEntity user);
    GroupEntity saveGroup(GroupEntity entity);
    boolean findByGroup(String teamName, String orgId);
    int updateUserGroupType(String userId, Long groupId, String type);
    void deleteMember(Long groupId, String memberId);
    void deleteGroup(Long groupId, String orgId);
    List<UserEntity> getMembers(String orgId, Long roleId);
    List<UserEntity> getMembersByRole(String orgId, List<Integer> higherRoleIds);
    List<GroupDto> getUserGroups(String userId, String orgId);
    List<UserGroupEntity> getGroupMembersByGroupId(Long groupId, String orgId);
    List<UserEntity> getUsersByIds(List<String> userIds, String orgId);
    Optional<UserEntity> findByMobileNumber(String mobileNumber);
    List<UserEntity> getAllUsers(String orgId, String userIdFromToken, int hierarchyLevel);
    UserEntity getUserById(String userId);
    boolean existsGroupNameInOrganization(String groupName, String orgId, Long groupId);
    UserGroupEntity saveUserGroup(UserGroupEntity entity);
    List<UserGroupEntity> findByUserIdAndGroupId(String userId, Long groupId);
    void deleteSupervisorsByGroupId(Long groupId, String userId);
    void deleteByGroupId(Long groupId);
    List<Long> findGroupIdsBySupervisorId(String userIdFromToken);
    List<GroupDto> getAllgroups(String orgId);
    List<UserEntity> findUsersByGroupIds(List<Long> groupIds);
    List<UserEntity> findMembersByGroupIds(List<Long> filteredGroupIds, String userIdFromToken);
    SecondaryDetailsEntity saveSecondaryDetails(SecondaryDetailsEntity secondaryDetails);
    Optional<SecondaryDetailsEntity> findByMobileByMobile(String mobile);
    Optional<SecondaryDetailsEntity> findByEmailByEmail(String email);
    List<UserNameSuggestionDto> searchUserNamesContaining(String keyword);
    Optional<RoleEntity> findRoleById(Long roleId);
    Optional<SecondaryDetailsEntity> findSecondaryUserById(String userId);
    boolean existsById(String userId);
    List<String> findSupervisorIdsByGroupId( Long groupId);
    Optional<GroupEntity> findByGroupId(Long groupId);
    List<String> findMemberIdsByGroupId(Long groupId);
    LocationEntity findLocationById(Long locationId, String orgId);
    List<RoleEntity> findAllWithPrivileges();
    List<UserGroupEntity> getGroupUsersByGroupId(List<Long> groupIds, String orgId);
    List<UserNameSuggestionDto> getAllActiveUsers(String orgId, int heirarchyLevel);
    List<UserNameSuggestionDto> getAllGroupUsers(List<Long> groupIds, String orgId);
    Set<String> getAllMobileNumbers(String orgId);
    Set<String> getAllEmails(String orgId);
    Map<String, Long> getRoleNameIdMap();
    Map<String, Long> getLocationNameToIdMap(String orgId);
    List<UserEntity> saveAllUsers(List<UserEntity> users);
    List<SecondaryDetailsEntity> saveAllSecondaryDetails(List<SecondaryDetailsEntity> details);
    Map<String, Long> getGroupNameIdMap(String orgId);
    List<UserGroupEntity> saveAllUserGroups(List<UserGroupEntity> userGroups);
    Set<String> getAllSecondaryEmail(String orgId);
    Set<String> getAllSecondaryMobile(String orgId);
    UserEntity findUserByOrgIdAndUserId(String orgId, String userId);
    LocationEntity addLocation(Location location);
    PrivilegeEntity addPrivilege(PrivilegeEntity privilegeEntity);
    Optional<PrivilegeEntity> findPrivilegeById(Long privilegeId);
    void saveRole(RoleEntity role);
    List<UserEntity> getUsersByRoles(Set<String> roles, String orgId);
    List<UserEntity> findUsersByRolesAndGroupIds(Set<String> roles, List<Long> supervisedGroupIds, String orgId);
    void saveUserLocation(List<UserLocationEntity> userLocationEntities);
    List<UserLocationEntity> findUserLocationByUserId(String userId);
    List<LocationEntity> findAllLocationById(List<Long> locationIds);
    void deleteUserLocationByUserId(String userId, Set<Long> toDelete);
    void updateUserLocationByUserId(List<UserLocationEntity>newEntities);
    List<UserGroupEntity> findUserGroupByUserId(String userId);
    void deleteUserGroupByUserId(String userId, Set<Long> toDelete);
    void updateUserGroupByUserId(List<UserGroupEntity> newEntities);
    List<LocationEntity> updateMultipleLocations(List<LocationEntity> updatedEntities);
    void deleteLocation(List<Long> locationIds, String orgId);
    Optional<LocationEntity> findAllDefaultLocationById(List<Long> locationIds, String orgId);
    LocationEntity findDefaultLocationByOrgId(String orgId);
    List<GroupEntity> findByLocation_LocationIdIn(List<Long> defaultLocationId);
    void saveAllGroups(List<GroupEntity> groupsToUpdate);
    List<UserLocationEntity> findUserLocationByLocationId(List<Long> defaultLocationId);
    Optional<OrganizationEntity> findByOrgId(String orgId);
    void updateUserWorkSchedule(String scheduleId, String scheduleId1);
    void updateGroupWorkSchedule(String scheduleId, String scheduleId1);
    OrganizationEntity create(OrganizationEntity entity);
    OrganizationEntity findByOrgName(String orgName);
    List<OrganizationTypeEntity> getAllOrgType();
    Long countOrganizations();
    boolean existsByOrganizationId(String orgId);
    List<LocationEntity> findLocation(String orgId);
    List<UserEntity> findUserByOrgIdAndRoleId(String orgId, int roleId);
    List<UserEntity> save(List<UserEntity> user);
    OrganizationTypeEntity findOrgType(String orgType);
    void saveAllUserLocation(List<UserLocationEntity> newUserLocationsToInsert);
    void deleteAllUserLocations(List<UserLocationEntity> userLocationsToDelete);
    List<UserGroupEntity> findUserByOrganizationIdAndUserId(String orgId, String userId);
    List<UserLocationEntity> findByUser_UserId(String userId);
    List<GroupEntity> findGroupLocationByLocationId(List<Long> locationIds);
    UserSchemaMappingEntity create(UserSchemaMappingEntity userSchemaMappingEntity);
    UserSchemaMappingEntity findUserByEmail(String email);
    UserSchemaMappingEntity findUserByMobile(String mobile);
    String findByPlan();
    SubscriptionEntity saveSubscription(SubscriptionEntity subscriptionEntity);
    void saveAllMappings(List<UserSchemaMappingEntity> mappings);
    void saveAllSecondaryMappings(List<UserSchemaMappingEntity> secondaryMappings);
    void saveUserFace(UserFaceEntity userFaceEntity);
    Optional<UserFaceEntity> findUserEmbeddingsById(String userId);
    Optional<LocationEntity> findLocationByLocationId(Long locationId);
    UserSchemaMappingEntity update(UserSchemaMappingEntity mapping);
    Optional<UserSchemaMappingEntity> findUserByMobileAndOrgId(String mobile, String orgId);
    void saveUserHistory(UserHistoryEntity userHistoryEntity);
    void deleteUserFace(String userId);
    List<UserHistoryEntity> getUserHistoryLog(String userId);
    List<UserLocationEntity> fetchLocationsForUser(String userId);
    List<UserEntity> searchUsers(String keyword);
}
